[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls-native-certs = "0.6.2"
native-tls = "0.2.10"
postgres = "0.19.4"
postgres-native-tls = "0.5.0"